package com.biorecorder.edflib.exceptions;

/**
 * Possible types of EdfHeaderRuntimeException.
 */
public enum ExceptionType {
    HEADER_NOT_FULL,
    VERSION_FORMAT_INVALID,
    DATE_FORMAT_INVALID,
    TIME_FORMAT_INVALID,
    RECORD_DURATION_NAN,
    RECORD_DURATION_NONPOSITIVE,
    NUMBER_OF_SIGNALS_NAN,
    NUMBER_OF_SIGNALS_NONPOSITIVE,
    SIGNAL_PHYSICAL_MIN_NAN,
    SIGNAL_PHYSICAL_MAX_NAN,
    SIGNAL_DIGITAL_MIN_NAN,
    SIGNAL_DIGITAL_MAX_NAN,
    SIGNAL_PHYSICAL_RANGE_INVALID,
    SIGNAL_DIGITAL_RANGE_INVALID,
    SIGNAL_DIGITAL_MIN_OUT_OF_PERMITED_RANGE,
    SIGNAL_DIGITAL_MAX_OUT_OF_PERMITED_RANGE,
    SIGNAL_NUMBER_OF_SAMPLES_IN_RECORD_NAN,
    SIGNAL_NUMBER_OF_SAMPLES_IN_RECORD_NONPOSITIVE
}
